# ??????? ? ?????????? ??????? META ??? RAG-??????????.
# ??????: ???_?????=????????
# ???? ???????? ? UTF-8. ?? ????????? ':' ? '=' ? ????????.

img_14.png=??????? ???????? ?????????? ???????? ???????
#img_13.png=??????? ???????? ?????????? ???????? ???????
img_50.png=?????????? ?????? ? ???????? ? ?? ?? 